apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    prometheus: "helloweb3-monitoring"
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'helloweb3'
        static_configs:
          - targets: ['helloweb3:3000'] 
            labels:
              app: 'helloweb3'