name: Build and Deploy to GCR

on:
  push:
    branches:
      - piyush-submission

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@main
        with:
          credentials_file: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use GCR
        run: |
          echo "gcr.io=${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcr-config.json"
          docker login -u _json_key --password-stdin https://gcr.io < "${HOME}/gcr-config.json"

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloweb3-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloweb3-app:${{ github.sha }}
